### ISSUE TITLE
Icons needed

### ISSUE THREAD

**Issue by ValorNaram** [Discostu36/Baby-Karte#10]
We need icons (symbols) for Babykarte. Where to get OR can we create these by ourselves?

**Comment by Discostu36** [comment]
I'm not artistic enough to create symbols from scratch, but I can try to find fitting ones with a free license

**Comment by ValorNaram** [comment]
Currently I am making my own icons for Babykarte. But please be patient and don't expect to much. It's likely I change these icons often since I improve myself in making icons. I am using inkscape and teach myself with some but rare help of tutorials.

**Comment by Discostu36** [comment]
The tabs in popups should be monochrome and only about 25 px high.

**Comment by Discostu36** [comment]
![unbenannt](https://user-images.githubusercontent.com/30999326/53017254-d7da9d00-344f-11e9-9928-9c84942e214c.png)

This is not really a good sketch but maybe you get an idea, what design I'm talking about. More like the little fixed tabs that you can get in Firefox or Chrome.

**Comment by ValorNaram** [comment]
I updated the repo with new icons made by myself. Please check out and feel free to comment on these.

**Comment by ValorNaram** [comment]
Your request of just 25px instead of 50px for the icons as I suggested were fullfilled within the last update of this repository.

**Comment by Discostu36** [comment]
It still doesn't really look like tabs, though.

**Comment by ValorNaram** [comment]
Are they looking now like tabs?

**Comment by ValorNaram** [comment]
Please open another issue when discussion about the tabs is needed,

**Now closing this**
