### ISSUE TITLE
Map not rendered

### ISSUE THREAD

**Issue by Discostu36** [Discostu36/Baby-Karte#11]
When using the current version I don't get any map at all:

![nomap](https://user-images.githubusercontent.com/30999326/52977348-34e13f00-33cd-11e9-83ca-fc55565c391b.png)

**Comment by ValorNaram** [comment]
what is your setup?Terminal command `python3 -m http.server 8080` and then opening http://localhost:8080/ in your browser should work. It works on my machine the same way.

**Comment by Discostu36** [comment]
MX Linux, Firefox. I did it like that and it worked with the former versions, but not this time. Map div is empty. The only error I got was a 404 for a missing favicon. I can try again tomorrow.

**Comment by ValorNaram** [comment]
then I may broke something. I will reupload in the hope the bug - then - will be solved.

**Comment by ValorNaram** [comment]
So I reuploaded almost all files. Now it should work.

Please close this issue when it works on your machine. Of course don't forget to fetch beforehand.

**Comment by Discostu36** [comment]
Works now.
