### ISSUE TITLE
Filter issues

### ISSUE THREAD

**Issue by Discostu36** [Discostu36/Baby-Karte#12]
A collection of small issues concerrning filters:

- [x] New filters only get added when clicking "Filter anwenden". The same behaviour should be used for removing filters.
- [x] The same is for filters that were already selected. Now they do appear immediately. I understand the reason behind that but it's not intuitive for the user.
- [x] The loading bar moves to the middle and stays there, when no content is found (no filter selected or no fitting POIs on the map)

**Comment by ValorNaram** [comment]
Close this please when the issues listed here are solved

**Comment by ValorNaram** [comment]
The repo has been already updated.
