### ISSUE TITLE
Changes to contact tab

### ISSUE THREAD

**Issue by Discostu36** [Discostu36/Baby-Karte#14]
- [x] Also provide telephone numbers and URLs as text next to the icons (list with Icon left and text right)
- [ ] Add social networks (Facebook, Instagram)

**Comment by ValorNaram** [comment]
**Request fullfilled!**

Remember: As more as you open issues as more as long I need for v.1 Consider to put some changes into v.2. I may consider to block further requests when they disturb me.

**Issue closed!**
