### ISSUE TITLE
Questions to the specification

### ISSUE THREAD

**Issue by ValorNaram** [Discostu36/Baby-Karte#17]
I have some questions regarding the specification:

    healthcare=birthing_center

What's that and how to name the filter?

    health_facility:type=counselling_centre, counselling_type:child_guidance=yes oder counselling_type:family=yes

What's that and how to name the filter?

**Comment by Discostu36** [comment]
### healthcare=birthing_center ###
A location where you can give birth that is not a hospital. 
Filter (DE): Geburtshäuser
Filter (EN): Birthing centers

### health_facility:type=counselling_centre ... ###
Counseling for parents. This is from an abandoned proposal but I don't know of a more common tag for this institutions.
Filter(EN): Counselling centres
Filter(DE): Beratungsstellen

**Comment by ValorNaram** [comment]
> A location where you can give birth that is not a hospital.

Such places exist?
<br/>
> Counseling for parents. This is from an abandoned proposal but I don't know of a more common tag for this institutions.

Are you really sure that you want to include a non standard tag? This is extremely discouraged as it can lead to wrong non-standard mapping of POI data

**Comment by Discostu36** [comment]
https://de.m.wikipedia.org/wiki/Geburtshaus

Ok, let's exclude counselling centres for the moment.

**Comment by ValorNaram** [comment]
Filter `Birthing centers` applied to Babykarte.
Filter `Counselling centres` **not** applied to Babykarte.

**Now closing this issue**
