### ISSUE TITLE
Url name

### ISSUE THREAD

**Issue by ValorNaram** [Discostu36/Baby-Karte#19]
It's time to specify the URl

I would suggest http://babykarte.github.io because `Babykarte` or `Baby-Karte` is the project title and the project title should be also the url name.

I don't suggest http://babymap.github.io because it would break the project title `Babykarte` or `Baby-Karte` and therefore not intuitive.

International doesn't matter because every western keyboard can write `babykarte` and the word is not as extremely difficult to remember. I see some spanish urls on the web and they aren't also difficult thought I don't remember these because I don't visit spanish websites so often.

**Comment by Discostu36** [comment]
I agree.
