### ISSUE TITLE
Filter lassen sich nicht deaktivieren

### ISSUE THREAD

**Issue by Discostu36** [Discostu36/Baby-Karte#4]
Eine Ebene anhaken und "Filter anwenden" klicken führt nicht zum Ausblenden dieser Ebene.

**Comment by ValorNaram** [comment]
Technisch gesehen sind die Filter keine Ebenen, da der Kaffeekarte-Code nicht mit Ebenen arbeitet. Der Cache Code kann nicht zwischen Ebene und nicht-Ebene unterscheiden, da dieser nur schon besuchte Koordinaten speichert und die neu hinzugekommenen Bereiche mithilfe eines langen komplexeren Algorythmus ermittelt und die Daten an den OSM Server weitergibt. Ich werde ein eigenes Ebenensystem entwickeln, da die Standartsysteme beim Verwenden der Karte mehr Daten an den Server senden würden.

Ich weiß leider noch nicht im Detail wie der Code aussehen wird noch kann ich meine Gedanken verschriftlichen. Die theoretische Entwicklung spielt sich in meinem Kopf an. Ich hoffe ich kann meinen Algorythmus irgendwann auf meinem Whiteboard verschriftlichen.

**Comment by ValorNaram** [comment]
Ist dieser Fehler behoben? Ich konnte immer noch nicht umfangreich testen, da ich noch keine Testreihen habe. Ich muss mal mein Whiteboard beanspruchen und diese niederschreiben.

**Comment by Discostu36** [comment]
Ja, der Bug besteht weiterhin.
