### ISSUE TITLE
Ladeanzeige

### ISSUE THREAD

**Issue by Discostu36** [Discostu36/Baby-Karte#6]
Es sollte angezeigt werden, ob die Karte gerade Daten lädt. Am einfachsten wahrscheinlich durch so einen kleinen Ladekreis. 

Zum Beispel den hier:
https://upload.wikimedia.org/wikipedia/commons/d/de/Ajax-loader.gif (Public Domain)

Könnte evt. neben der Filterliste angezeigt werden

**Comment by ValorNaram** [comment]
Soll ich diesen Ladebalken nehmen oder dem Ladebalkentrend von Google bzw. Youtube und Co folgen?

**Comment by Discostu36** [comment]
Ich bin da leidenschaftslos. Mach, was dir besser gefällt und/oder einfacher zu implementieren ist.

**Comment by mondstern** [comment]
Bei der unterkunftskarte gibt's auch diesen kleinen ladekreis. Das ist ok
