### ISSUE TITLE
Create possibility for internationalization 

### ISSUE THREAD

**Issue by Discostu36** [Discostu36/Baby-Karte#9]
v1.0 can be in German only but the code should include the possibility for easily translating all strings to other languages.

**Comment by ValorNaram** [comment]
Should Babykarte itself be international useable? Meaning including all the languages it should support.

OR

should it be that someone can easily fork and easily change the language and then reupload- and maintaining it without us?

**Comment by Discostu36** [comment]
I think that in the long run Babykarte should at least have an English language option and the possibility to easily create pull requests for adding more language options.

**Comment by ValorNaram** [comment]
Currently Babykarte detects the language of the browser automatically. It is a wanted behaviour or should the user decide which language he/she/it wants to use?

OR

should the user decide which language he/she/it wants to use after the detecting process. Or should display Babykarte its german user interface without detecting the language of the user but with the possibilities to change language by clicking on an icon?

**Issue NOT closed**

**Comment by Discostu36** [comment]
Babykarte should automatically detect the browser language with the possibility to change language by clicking on an icon.

**Comment by ValorNaram** [comment]
Do you know a place where I can get little copyright free language icons?

**Comment by Discostu36** [comment]
Maybe at Pixabay? Are we talking about national flags or what is a language icon for you?

**Comment by ValorNaram** [comment]
National flags

**Comment by Discostu36** [comment]
National flags don't have a copyright. You could use SVGs from here:

https://commons.wikimedia.org/wiki/Category:SVG_flags_by_country

**Comment by Discostu36** [comment]
I think in the long run the different strings should be in a separate file. So that a contributor only needs to upload a fr.json and link it from index.html

**Comment by ValorNaram** [comment]
Linking #2 to this issue

**Comment by ValorNaram** [comment]
Issue solved!
